Number.prototype.formatMoney = function(c, d, t){
var n = this, c = isNaN(c = Math.abs(c)) ? 2 : c, d = d == undefined ? "," : d, t = t == undefined ? "." : t, s = n < 0 ? "-" : "", i = parseInt(n = Math.abs(+n || 0).toFixed(c)) + "", j = (j = i.length) > 3 ? j % 3 : 0;
   return s + (j ? i.substr(0, j) + t : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : "");
 };
var age = 0;
var sex = "M";//M/F
var kids = 0;//number of kids
var parents = 0;//number of parent
var monthlyIncome = 0;//monthly income
var spouse = "Y";//spouse working or not
var currentlyInsured = 0;//currently insured

/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the widget is ready to start
//
function load()
{
    dashcode.setupParts();
    doInit();
}

//
// Function: remove()
// Called when the widget has been removed from the Dashboard
//
function remove()
{
    // Stop any timers to prevent CPU usage
    // Remove any preferences as needed
    // widget.setPreferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
}

//
// Function: hide()
// Called when the widget has been hidden
//
function hide()
{
    // Stop any timers to prevent CPU usage
}

//
// Function: show()
// Called when the widget has been shown
//
function show()
{
    // Restart any timers that were stopped on hide
    //hide conteact us and wz bar
}

function doInit() {
    var contactus = document.getElementById("ContactUsPlacer");
    var wzbar = document.getElementById("WizzardBarPlacer");
    contactus.style.display = "none";
    wzbar.style.display = "none";
    
    
    age = 20;
    sex = "M";//M/F
    kids = 2;//number of kids
    parents = 0;//number of parent
    monthlyIncome = 5000;//monthly income
    spouse = "N";//spouse working or not
    currentlyInsured = 0;//currently insured
    
    q2Slider.value = age - 20;
    q5Slider.value = kids;
    q6Slider.value = parents;
    q7Slider.value = 0;
    q4Slider.value = monthlyIncome / 500;
    
    
    q2AgeDisplay.innerText = "20";
    q5ChildDisplay.innerText = kids;
    q6ParentDisplay.innerText = parents;
    q7InsuredDisplay.innerText = "$0";
    q4IncomeDisplay.innerText = "$5,000";
    q4IncomeDisplay.style.left = 272 + ((monthlyIncome / 500 - 1) * 12) + "px";
    q5ChildDisplay.style.left = 295 + (kids * 84) + (kids > 3 ? -10 : 0) + "px";
    /*
    q2Slider.innerText = "20";
    q4IncomeDisplay.innerText = "$0";
    q5ChildDisplay.innerText = "0";
    q6ParentDisplay.innerText = "0";
    q7InsuredDisplay.innerText = "$0";
    */
    //hide all question screen
    document.getElementById("Question1Screen").style.display = "none";
    document.getElementById("Question2Screen").style.display = "none";
    document.getElementById("Question3Screen").style.display = "none";
    document.getElementById("Question4Screen").style.display = "none";
    document.getElementById("Question5Screen").style.display = "none";
    document.getElementById("Question6Screen").style.display = "none";
    document.getElementById("Question7Screen").style.display = "none";
    document.getElementById("YReportScreen").style.display = "none";
}

//
// Function: sync()
// Called when the widget has been synchronized with .Mac
//
function sync()
{
    // Retrieve any preference values that you need to be synchronized here
    // Use this for an instance key's value:
    // instancePreferenceValue = widget.preferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
    //
    // Or this for global key's value:
    // globalPreferenceValue = widget.preferenceForKey(null, "your-key");
}

if (window.widget) {
    widget.onremove = remove;
    widget.onhide = hide;
    widget.onshow = show;
    widget.onsync = sync;
}


function letFindoutHandler(event)
{
    // Insert Code Here
    var landing = document.getElementById("LandingScreen");
    var inotes = document.getElementById("ImportantNotesScreen");
    var contactus = document.getElementById("ContactUsPlacer");
    inotes.style.display="block";
    landing.style.display="none";
    //show contact us
    contactus.style.display = "block";
}


function bbtnContinueImportantNotesScreenHandler(event)
{
    // Insert Code Here
    var q1 = document.getElementById("Question1Screen");
    var inotes = document.getElementById("ImportantNotesScreen");
    inotes.style.display="none";
    q1.style.display="block";
    
    var contactus = document.getElementById("ContactUsPlacer");
    var wzbar = document.getElementById("WizzardBarPlacer");
    //show wzbar and contact us
    contactus.style.display = "block";
    wzbar.style.display = "block";
    
    gotoQuestion(1);
}


function q1MaleImgClicked(event)
{
    // Insert Code Here
    //widget.setPreferenceForKey("1", dashcode.createInstancePreferenceKey("q1"));
    var fmimg = document.getElementById("q1_img_female").firstChild;
    var mimg = document.getElementById("q1_img_male").firstChild;
    mimg.src = "Images/q_1_male_a~ipad.png";
    fmimg.src= "Images/q_1_female_n~ipad.png";
    sex = "M";
}


function q1FemaleImgClicked(event)
{
    // Insert Code Here
    //widget.setPreferenceForKey("0", dashcode.createInstancePreferenceKey("q1"));
    var fmimg = document.getElementById("q1_img_female").firstChild;
    var mimg = document.getElementById("q1_img_male").firstChild;
    mimg.src = "Images/q_1_male_n~ipad.png";
    fmimg.src = "Images/q_1_female_a~ipad.png";
    sex = "F";
}

function gotoQuestion(qno) {
    document.getElementById("YReportScreen").style.display = "none";
    var qplacer = document.getElementById("WizzardBarPlacer");
    qplacer.style.display = "block";
    for(var i = 1 ; i <= 7 ; ++i) {
        var qplacer = document.getElementById("Question" + i + "Screen");
        if (i != qno) {
            qplacer.style.display = "none";
        }
        //then need to update active question btn also
        var btnplacer = document.getElementById("wz_btn_q" + i).firstChild;
        if (i != qno) {
            btnplacer.src = "Images/step-" + i + "-n~ipad.png";
        }    
    }
    var qplacer = document.getElementById("Question" + qno + "Screen");
    qplacer.style.display = "block";
    var btnplacer = document.getElementById("wz_btn_q" + qno).firstChild;
    btnplacer.src = "Images/step-" + qno + "-a~ipad.png";
}

function getComputedLeft(me) {
    return parseInt(document.defaultView.getComputedStyle(me, '').getPropertyValue("left"), 10);
}

function wzStep1ClickedHandle(event)
{
    // Insert Code Here
    gotoQuestion(1);
}

function q6SliderChanged(currentValue) {
    
    var currentValue = parseInt(q6Slider.value);
    var q6ParentDisplay = document.getElementById("q6ParentDisplay");
    q6ParentDisplay.style.left = 339 + (currentValue * 85) + (currentValue > 3 ? -10 : 0) + "px";
    q6ParentDisplay.innerText = currentValue;
    
    //checking display image
    var q5Thumb = document.getElementById("q6_img_thumb").firstChild;
    q5Thumb.src = "Images/q_6_family" + currentValue + "~ipad.png";
    
    //assign public var
    parents = currentValue;
}



function q5SliderChanged(obj) {
    var currentValue = parseInt(q5Slider.value);
    var q5ChildDisplay = document.getElementById("q5ChildDisplay");
    q5ChildDisplay.style.left = 295 + (currentValue * 84) + (currentValue > 3 ? -10 : 0) + "px";
    q5ChildDisplay.innerText = currentValue;
    
    //checking display image
    var q5Thumb = document.getElementById("q5_img_thumb").firstChild;
    q5Thumb.src = "Images/q_5_child" + currentValue + "~ipad.png";
    
    //assign public param
    kids = currentValue;
}

function q4SliderChanged(obj) {
    var q4IncomeDisplay = document.getElementById("q4IncomeDisplay");
    var currentValue = parseInt(q4Slider.value);
    q4IncomeDisplay.style.left = 272 + (currentValue > 0 ? (currentValue - 1) * 12 : 0) + "px";
    var insured = 0;
    if (currentValue <=36) {
        insured =  (currentValue * 500);
    }else{
        insured = ((currentValue - 1) * 500 + 500);
    }
    q4IncomeDisplay.innerText = "$" + (insured).formatMoney(0, '.', ',');
    //checking display image
    var q4Thumb = document.getElementById("q4_img_thumb").firstChild;
    if (currentValue <= 10) {
        q4Thumb.src = "Images/q_4_money1~ipad.png";
    }else if (currentValue <= 20) {
        q4Thumb.src = "Images/q_4_money2~ipad.png";
    }else{
        q4Thumb.src = "Images/q_4_money3~ipad.png";
    }
    
    //assign param
    monthlyIncome = insured;
}

function q2SliderChanged(obj){
    var currentValue = parseInt(q2Slider.value);
    // Do something with the currentValue passed in
    var q2AgeDisplay = document.getElementById("q2AgeDisplay");
    q2AgeDisplay.innerText = (20 + currentValue);
    q2AgeDisplay.style.left = 287 + (currentValue > 0 ? (currentValue - 1) * 9.7 : 0) + "px";
    //alert(q2AgeDisplay.style.left);
    //checking display image
    var q2Thumb = document.getElementById("q2_img_thumb").firstChild;
    if (currentValue < 9) {
        q2Thumb.src = "Images/q_2_man1~ipad.png";
    }else if (currentValue <= 29) {
        q2Thumb.src = "Images/q_2_man2~ipad.png";
    }else{
        q2Thumb.src = "Images/q_2_man3~ipad.png";
    }
    
    //assign params
    age = (20 + currentValue);
}

function wzStep2ClickedHandle(event)
{
    // Insert Code Here
    gotoQuestion(2);
    //then we need to replace thumb
    //debug event here
    var q2Slider = document.getElementById("slider");
    //for (var i in q2Slider) {
        //alert(i);
    //}
    //q2Slider.setThumb("Images/handle~ipad.png", 72);
    //q2Slider.setTrackMiddle("Images/handle~ipad.png");
}


function wzStep3ClickedHandle(event)
{
    // Insert Code Here
    gotoQuestion(3);
}


function wzStep4ClickedHandle(event)
{
    // Insert Code Here
    gotoQuestion(4);
}


function wzStep5ClickedHandle(event)
{
    // Insert Code Here
    gotoQuestion(5);
}


function wzStep6ClickedHandle(event)
{
    // Insert Code Here
    gotoQuestion(6);
}


function wzStep7ClickedHandle(event)
{
    // Insert Code Here
    gotoQuestion(7);
}


function wzYReportClickedHandle(event)
{
    // Insert Code Here
    var pn = calculateProtectionNumberV2();
    var pgap = pn - currentlyInsured;
    //alert("pgap " + pgap);
    for(var i = 1 ; i <= 7 ; ++i) {
        var qplacer = document.getElementById("Question" + i + "Screen");
        qplacer.style.display = "none";
    }
    var qplacer = document.getElementById("YReportScreen");
    qplacer.style.display = "block";
    var qplacer = document.getElementById("WizzardBarPlacer");
    qplacer.style.display = "none";
    
    //update number
    txtYPN.innerText = "$" + (pn).formatMoney(0, '.', ',');
    txtPG.innerText = "$" + (pgap).formatMoney(0, '.', ',');
    if (pgap > 0) {
        lblPG.style.display = "block";
        txtPG.style.display = "block";
        lblWithGap.style.display = "block";
        lblWithoutGap.style.display = "none";
    }else{
        //does not has gap
        lblPG.style.display = "none";
        txtPG.style.display = "none";
        lblWithGap.style.display = "none";
        lblWithoutGap.style.display = "block";
    }
}


/*clickedValue: 1: yes 0: No, 2: Unmarried*/
function updateQ3Thumb(clickedValue) {
    var yesImg = document.getElementById("q3_yes_img").firstChild;
    var noImg = document.getElementById("q3_no_img").firstChild;
    var unImg = document.getElementById("q3_un_img").firstChild;
    yesImg.src = (clickedValue == 1 ? "Images/q_3_yes_a~ipad.png" : "Images/q_3_yes_n~ipad.png");
    noImg.src = (clickedValue == 0 ? "Images/q_3_no_a~ipad.png" : "Images/q_3_no_n~ipad.png");
    unImg.src = (clickedValue == 2 ? "Images/q_3_un_a~ipad.png" : "Images/q_3_un_n~ipad.png");
}

function q3YesClickedHandler(event)
{
    // Insert Code Here
    updateQ3Thumb(1);
    spouse = "Y";
}


function q3NoClickedHandler(event)
{
    // Insert Code Here
    updateQ3Thumb(0);
    spouse = "N";
}


function q3UnClickedHandler(event)
{
    // Insert Code Here
    updateQ3Thumb(2);
    spouse = "n/a";
}


function q7SliderChanged(event)
{
    // Insert Code Here
    var currentValue = parseInt(q7Slider.value);
    // Do something with the currentValue passed in
    var q2AgeDisplay = document.getElementById("q7InsuredDisplay");
    var insured = 0;
    if(currentValue <= 2) {
        insured = currentValue * 5000;
    } else if(currentValue <= 6) {
        //(ui.value-1) * 10000
        insured = (currentValue-1) * 10000;
    } else if(currentValue <= 16) {
        insured = (50000 + (currentValue-6) * 5000);//(50000 + (ui.value-6) * 5000)
    } else if(currentValue <= 24) {
        insured = (100000 + (currentValue-16) * 50000);//(100000 + (ui.value-16) * 50000)
    } else if(currentValue <= 29) {
        insured = (500000 + (currentValue-24) * 100000);//(500000 + (ui.value-24) * 100000)
    } else if(currentValue <= 39) {
        insured = (1000000 + (currentValue-29) * 100000) ; //(1000000 + (ui.value-29) * 100000)
    } else if(currentValue <= 49) {
        insured = (2000000 + (currentValue-39) * 100000);//(2000000 + (ui.value-39) * 100000)
    }
    
    
    q2AgeDisplay.innerText = "$" + (insured).formatMoney(0, '.', ',');
    q2AgeDisplay.style.left = 265 + (currentValue > 0 ? (currentValue - 1) * 9.9 : 0) + "px";
    
    //checking display image
    var q7Thumb = document.getElementById("q7_img_thumb").firstChild;
    if (currentValue < 6) {
        q7Thumb.src = "Images/q_8_insured1~ipad.png";
    }else if (currentValue <= 24) {
        q7Thumb.src = "Images/q_8_insured2~ipad.png";
    }else{
        q7Thumb.src = "Images/q_8_insured3~ipad.png";
    }
    
    //assign param
    currentlyInsured = insured;
}


function goBack2TweakAnswers(event)
{
    // Insert Code Here
    gotoQuestion(1);
}
